version: '3'

services:
  fluentd:
    build: ./fluentd
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /opt/efk/fluentd/log:/fluentd/log
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - es-nt
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=master1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/efk/es/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es-nt

  kibana:
    image: kibana:7.6.0
    container_name: elk_kibana
    environment:
      - server.name=kibana
      - server.host=0.0.0.0
      - elasticsearch.hosts="http://172.26.0.2:9200"
    restart: always
    ports:
      - "5601:5601"
    networks:
      - es-nt
    privileged: true    #环境变量

networks:
  es-nt:
